---
# ─── 台式机独有配置 ───

hostname: desktop-arch-i712700

# 台式机专用包（Intel 驱动）
packages_extra:
  - vulkan-intel
  - intel-media-driver

# 网络（静态 IP）
static_ip: 192.168.10.25

# 显示器
monitors:
  - name: DP-3
    scale: 2
