---
# ─── 笔记本独有配置 ───

hostname: laptop-arch-p50

# 网络
network_interface: wlan0
static_ip: 192.168.10.26

# 笔记本专用包
packages_extra:
  - brightnessctl
  - iwd

# 笔记本专用服务
services_extra:
  - iwd

# WiFi
wifi_ssid: FAST_0094

# 笔记本特有
lid_close_action: ignore

# 显示器
monitors:
  - name: eDP-1
    scale: 1.5
